# Generated by Django 2.2.13 on 2022-09-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20220922_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('category_image', models.CharField(blank=True, max_length=100, null=True)),
                ('category_description', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(db_column='Description')),
                ('selling_price', models.FloatField()),
                ('tag', models.CharField(max_length=150)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_description', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'c_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(db_column='Description')),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_description', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'c_types',
                'managed': False,
            },
        ),
    ]
